#!/usr/bin/env node
/**
 * Renders the curriculum seed content (validated via loadSeedContent) as a
 * plain, idempotent .sql file — the same statements seedContent() would
 * run via Db.batch(), just serialized for `wrangler d1 execute` instead of
 * a live binding (this dev machine can't run `wrangler dev`/`d1` locally
 * at all; see README.md). Usage:
 *
 *   node --experimental-strip-types apps/api/scripts/generateSeedSql.ts > /tmp/curriculum_seed.sql
 *   wrangler d1 execute DB --local --file=/tmp/curriculum_seed.sql
 *   wrangler d1 execute DB --remote --file=/tmp/curriculum_seed.sql   # preview/production
 *
 * Safe to run repeatedly against the same database — every statement is
 * an upsert.
 */
import { loadSeedContent } from "../src/content/loadSeedContent.ts";
import { buildSeedStatements } from "../src/content/buildSeedStatements.ts";

function sqlLiteral(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return String(value);
  return `'${String(value).replace(/'/g, "''")}'`;
}

function renderStatement(sql: string, params: unknown[] = []): string {
  let i = 0;
  const rendered = sql.replace(/\?/g, () => sqlLiteral(params[i++]));
  return `${rendered.trim()};`;
}

const bundle = loadSeedContent();
const now = new Date().toISOString();
const statements = buildSeedStatements(bundle, now);

const lines = [
  "-- Generated by apps/api/scripts/generateSeedSql.ts — do not hand-edit.",
  "-- Idempotent: safe to apply more than once.",
  "PRAGMA foreign_keys = ON;",
  "",
  ...statements.map((s) => renderStatement(s.sql, s.params)),
];

process.stdout.write(lines.join("\n") + "\n");
